date.timezone = Asia/Tokyo
##エラー表示の有無（開発になったらoffにする）
display_errors = On
error_reporting = E_ALL
upload_max_filesize = 20M
post_max_size = 20M
memory_limit = 256M

##マルチバイト
[mbstring]
mbstring.internal_encoding = "UTF-8"
mbstring.language = "Japanese"
