server {
    listen 80;
    ##http://localhost/にアクセスしたときに接続する順番
    index index.php index.html;
    ##本番では名前の変更
    server_name localhost;
    ##laravelの入口はpublic
    root /var/www/public;
    client_max_body_size 10M;

    ##http://localhost/userにアクセスしたときになければindex.phpへ
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    ##セキュリティ
    location ~ /\.ht {
        deny all;
    }
}